sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.223.142
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  wechat:
    appid: wx37a1bf32426ae2dd
    secret: 7b50cd775720718d51597528cc9cebfd
