---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 28937.
--- DateTime: 2024/12/14 16:14
---
-- 定义 Lua 脚本
local key = KEYS[1]  -- 获取传入的 key（token 值）

-- 检查 key 是否存在
if redis.call("EXISTS", key) == 1 then
    -- 如果存在，删除该 key
    redis.call("DEL", key)
    return 1  -- 返回 1 表示删除成功
else
    return 0  -- 返回 0 表示 key 不存在
end